CREATE TABLE patients (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    phone VARCHAR(20) NOT NULL,
    cpf VARCHAR(14) NOT NULL UNIQUE,
    street VARCHAR(100) NOT NULL,
    neighborhood VARCHAR(100) NOT NULL,
    zip_code VARCHAR(9) NOT NULL,
    complement VARCHAR(100),
    number VARCHAR(20),
    state VARCHAR(2) NOT NULL,
    city VARCHAR(100) NOT NULL,
    active TINYINT NOT NULL DEFAULT 1,
    PRIMARY KEY (id)
);
